name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: jfermat/angular-deploy-gh-pages-actions
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN_PUBLICAR }}
        base_href: /  
        deploy_repo: venturasimo/venturasimo.github.io
        deploy_branch: main 
        angular_dist_build_folder: dist/